{
 "title": "SLI Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime Frontend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg by(namespace) (avg_over_time(up{namespace=\"default\", pod=~\"frontend-app-.*\"}[24h]))",
     "legendFormat": "Uptime Frontend"
    }
   ]
  },
  {
   "title": "Uptime Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * avg by(namespace) (avg_over_time(up{namespace=\"default\", pod=~\"backend-app-.*\"}[24h]))",
     "legendFormat": "Uptime Backend"
    }
   ]
  },
  {
   "title": "50x Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"50(0|1|2|3|4|5)\", job=\"frontend-service\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_total{status=~\"50(0|1|2|3|4|5)\", job=\"backend-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_total{status=~\"50(0|1|2|3|4|5)\", job=\"trial-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "40x Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"40(0|1|2|3|4|5)\", job=\"frontend-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_total{status=~\"40(0|1|2|3|4|5)\", job=\"backend-service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_total{status=~\"40(0|1|2|3|4|5)\", job=\"trial-service\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}